AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 3 API - dev.guvenx::spring-boot-serverless
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  SpringBootServerlessFunction:
    Type: AWS::Serverless::Function
    Properties:
      SnapStart:
        ApplyOn: PublishedVersions
      Handler: dev.guvenx.StreamLambdaHandler::handleRequest
      Runtime: java21
      CodeUri: target/spring-boot-serverless-1.0-SNAPSHOT-aws.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  SpringBootServerlessApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: SpringBootServerlessApi
